### ISSUE TITLE
[Bug]: Tablet version

### ISSUE THREAD

**Issue by Da-PC** [OTTAA-Project/ottaa_project_flutter#222]
### Branch name

development

### Flutter & Dart version

Flutter version 3.7.3 stable Dart  2.19.2

### How are you running it?

My steps are flutter 

flutter run
Use the app

### What happened?

A bug happened! When trying to display more than 4 pictograms, but does not happen every time. 

Also the app opens in Spanish even though the device is in English. 
Device lang: English US

Action plan:

- [ ] Rotate onboarding to fit on landscape mode
- [ ] Fix margins and button layout
- [ ] Make Pictos bigger, should only fit 4.

 
![Screenshot_1679336574](https://user-images.githubusercontent.com/127154933/226434167-9624e3b5-7726-49f8-b32f-101e9c31eade.png)

![Screenshot_1679336586](https://user-images.githubusercontent.com/127154933/226434245-060bd29f-00e2-4ae4-b41d-d3875ae1b90a.png)

![Screenshot_1679336621](https://user-images.githubusercontent.com/127154933/226434196-d3ac4acf-b131-4c7a-94b8-2f9642f7a873.png)

![Screenshot_1679336653](https://user-images.githubusercontent.com/127154933/226434227-65726838-8f16-42ba-a193-38fd84834df3.png)

### Where are you seeing the problem on?

Android

### Relevant log output

```shell
======== Exception caught by widgets library =======================================================
The following RangeError was thrown building:
RangeError (index): Invalid value: Not in inclusive range 0..3: 5

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      _PictosBarState.buildWidgets.<anonymous closure> (package:ottaa_project_flutter/presentation/screens/home/ui/pictos_bar.dart:129:27)
#2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:487:22)
#3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1422:28)
#4      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1352:67)
#5      Iterable.forEach (dart:core/iterable.dart:325:35)
#6      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1399:24)
#7      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1328:7)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#11     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#15     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5981:32)
#16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#27     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#29     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#35     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#41     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#51     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#54     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#56     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#59     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#61     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#65     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#69     StatelessElement.update (package:flutter/src/widgets/framework.dart:5044:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#73     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#75     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5981:32)
#76     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#80     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#82     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5981:32)
#83     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#86     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#88     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#89     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#90     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#91     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#92     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#93     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#94     _invoke (dart:ui/hooks.dart:145:13)
#95     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#96     _drawFrame (dart:ui/hooks.dart:112:31)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
@emirchus is the onboarding rotated? What are we going to do with it

**Comment by aguszanoli** [comment]
Missing things @emirchus tested on a Nexus 10 emulator.

- [x] The signin button looks very stretched, you should add some margins to it as did with the rest of the UI
![Image](https://user-images.githubusercontent.com/116307075/236329664-d03ac192-a34e-4c1d-99e9-e6285982dbf3.png)

- [x] Force landscape mode on Tablets when onboarding.
- [x] The buttons on Search dont have proper margins

![Image](https://user-images.githubusercontent.com/116307075/236330113-5a4512fb-7220-4681-a089-07c821f90f4e.png)

- [x] The icon in the button is too small. Also search and more buttons are really small

![Image](https://user-images.githubusercontent.com/116307075/236330312-d0617b10-7d54-474c-aedb-fe94218f855c.png)

**Comment by emirchus** [comment]
Ready, all should be done @aguszanoli @hectoritr
