### ISSUE TITLE
[Bug]: Error on language in user map

### ISSUE THREAD

**Issue by Da-PC** [OTTAA-Project/ottaa_project_flutter#226]
### Branch name

Settings-screen#191

### Flutter & Dart version

Flutter version 3.7.3 stable Dart  2.19.2

### How are you running it?

Run the app

### What happened?

A bug happened! It hangs on the onboarding process.

### Relevant log output

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'LanguageSetting' is not a subtype of type 'Map<dynamic, dynamic>'
E/flutter ( 8567): #0      new BaseSettingsModel.fromMap (package:ottaa_project_flutter/core/models/base_settings_model.dart:47:118)
E/flutter ( 8567): #1      new CaregiverUserModel.fromMap (package:ottaa_project_flutter/core/models/caregiver_user_model.dart:74:35)
E/flutter ( 8567): #2      ProfileNotifier.settingUpUserType (package:ottaa_project_flutter/application/providers/profile_provider.dart:100:36)
E/flutter ( 8567): #3      _ProfileWaitingScreenState.initState.<anonymous closure> (package:ottaa_project_flutter/presentation/screens/profile/ui/profile_waiting_screen.dart:26:22)
E/flutter ( 8567): #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
E/flutter ( 8567): #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
E/flutter ( 8567): #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
E/flutter ( 8567): #7      _invoke (dart:ui/hooks.dart:145:13)
E/flutter ( 8567): #8      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
E/flutter ( 8567): #9      _drawFrame (dart:ui/hooks.dart:112:31)
E/flutter ( 8567):
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asimjawad** [comment]
** flutter packages pub run build_runner build --delete-conflicting-outputs**

did you create the models with this before running the app?
