### ISSUE TITLE
Bug: Loading User data

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#64]
**Screenshot of the feature to be developed.**
 

**Additional context**
I've been using it on Tablet emulator, then switched to Mobile emulator and got the error. 

I/flutter (12105): the value from stream is OTTAA Project
I/flutter (12105): the result is for file : true
I/flutter (12105): from file user first time: mobile
I/flutter (12105): the value from stream is OTTAA Project
I/flutter (12105): the result is for file : null
I/flutter (12105): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (12105): NoSuchMethodError: The method '[]' was called on null.
I/flutter (12105): Receiver: null
I/flutter (12105): Tried calling: []("data")
I/flutter (12105): 
I/flutter (12105): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
I/flutter (12105): #1      FirebaseDatabaseService.mobileFiles (package:ottaa_project_flutter/app/data/service/firebase_database_service.dart:227:31)
I/flutter (12105): <asynchronous suspension>
I/flutter (12105): #2      FirebaseDatabaseService.fetchGrupos (package:ottaa_project_flutter/app/data/service/firebase_database_service.dart:195:14)
I/flutter (12105): <asynchronous suspension>
I/flutter (12105): #3      FirebaseDatabaseRepository.fetchGrupos (package:ottaa_project_flutter/app/data/repositories/firebase_database_repository.dart:16:7)
I/flutter (12105): <asynchronous suspension>
I/flutter (12105): #4      DataController.fetchGrupos (package:ottaa_project_flutter/app/global_controllers/data_controller.dart:15:7)
I/flutter (12105): <asynchronous suspension>
I/flutter (12105): #5      GrupoService.getAll (package:ottaa_project_flutter/app/data/service/grupo_service.dart:9:12)
I/flutter (12105): <asynchronous suspension>
I/flutter (12105): #6      HomeController.loadPicts (package:ottaa_project_flutter/app/modules/home/home_controller.dart:243:19)
I/flutter (12105): <asynchronous suspension>
I/flutter (12105): #7      HomeController.onInit (package:ottaa_project_flutter/app/mod

**Comment by hectoritr** [comment]
Closed because of the new UI.
